language: node_js
node_js:
  - stable
  - "0.12"
notifications:
  email: false
script: npm test
after_success:
  - 'gulp coveralls'
# deploy:
#   provider: npm
#   email: patricksissons@gmail.com
#   api_key:
#     secure: `travis encrypt YOUR_API_KEY --add deploy.api_key`
#   on:
#     branch: master
#     repo: patsissons/hubot-giphy
