language: node_js
node_js:
  - stable
  - '0.12'
notifications:
  email: false
script: npm test
deploy:
  provider: npm
  email: patricksissons@gmail.com
  on:
    branch: master
  api_key:
    secure: j0skqUBmRKHAqGozVXsw6kYTPDLwHSPVt0jzJOHZrLX1UsmjQBo0/oGdLYNe/qjh3u8kTmtuf4C0GFy14yX/ePrZSSmA+zejGAJwgB+/kI1pRQdl7P8NeD9t4NflNmGEvZi9HYq5fHnDzRJ/201FHGu4L3gNqdivqx/dsHa5InEqM10HnOySFdTKsCkU8mR9IuKXZhEfwIe6JPcjCxzkZFWJ9E5dileaJtNrKPD+htOBVLSlQFw9Ilr1EQIPiTVQP6jzWAEm9kDmkFmXVrDxW/xCwgqcZjzKp4TwhLBG1pJ4E9QbRd9De07LeqY0Dz8z8BBYYKoF0Kc8wUQXTtiug5Iwie8f1gzJS99hcbkZDjP2CizE4NWWGIBpy9UT8Q3peeRxvFUxiARjrjK1Aiz3LGJgGhFsxdnKimHd5MEAND/O2oaT6E6ejFiQvieOQofIk7hgKfCq6r0onnvawmU2EHlZbO68mlIUHOlcPa/ST3lnSlqczMdVjf2U1etzpnghbf6uwI6DTEBgyQuUPGXmqaEqzPmznvOeb6sRGLbdREARVC54Zh96+/TbLR2pgjY+3vL6R7Gbvvs1fVUAxfO2vYK8/UEMoaMoVovpBuTaWA3Idz14KSNiRYlpgOZevt2a1fTZ8PBXCeqWJ9fEFsHJ7AlPJ1g0Nxv7h7TIJNfD3R8=
