language: node_js
node_js:
  - stable
  - '0.12'
notifications:
  email: false
script: npm test
deploy:
  provider: npm
  email: patricksissons@gmail.com
  'on':
    branch: master
    repo: patsissons/hubot-giphy
  api_key:
    - secure: >-
        epImFuB5UpbOtmMe+KRnyZHF3MB7pkpMo4dpRtQJrHnQ20Yx3RtZZBm+H5Phk5qii5g9pfxfAgXabQLZuwYTFEPtK3cJc5cNWf+T0dnLHqvB5cRO7U3hfUxV+mJ9+vgZnd/WN8h5Yp6FP8mgO3Mex5fjoON+KXCJzdE9yCOQpKN1/6FSZBZf/36xCI6z3qJQ5tmnm0aCkXcE5nlTGXyBya3SHF39ZzMfa6xVhHQJlnyS/KVHeVWXGDw109V9pikaHeuAEizu2FNd1xP04aCIluB/LDVaGnkYPCc17sHfQCM/U89O/bJk2laS6/QjsHlAopchXgN9kn1vKzrW7DlqX1g5oo5cJ+i69QSV2zZdbQRxsDb4oSbWirbolBZifx98BPEHJN8tCnye0wgOpL+bvUFX2+CbJ/QWPYppFE4MVpm+EHnytXFoZvx4K9Mp+5zJAgzb7K2EBS2p1SWOd8onyeEb4E/pPeFTbO2mxURQ0IhZSRkZsor36Mc6tanWbnQLjhaWcwXACU33e6RSVoB4NtkLE/oMCd9TBgl1Pp8ckxnfHIca5z21UGFGKNHHeGqTKLfTXJGBNpLyi2lBwMS3F9LgwrIDoLuD+lHVz5QubzD5K/3VNkGRgMa1Md7d33GD5RdXCUUfjjdkCfC3qYEyULzdlIyHmf9gdyE5kp25904=
